---
traefik__image: docker.io/traefik:v3.1.0

traefik__ports:
  - 80:80
  - 443:443

traefik__dir: /opt/traefik

traefik__routes: {}

traefik__acme_email: ljurk@pm.me
traefik__config:
  api:
    dashboard: false
    insecure: false
  log:
    level: INFO
    format: common
  accessLog:
    format: common
  entryPoints:
    http:
      address: ":80"
    https:
      address: ":443"
  providers:
    file:
      filename: /etc/traefik/routes.yml
      watch: true
  certificatesResolvers:
    letsencrypt:
      acme:
        email: "{{ traefik__acme_email }}"
        storage: /acme/acme.json
        httpChallenge:
          entryPoint: http
