---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/miniflux
    - /opt/miniflux/db

- name: Start container
  containers.podman.podman_container:
    name: db
    image: docker.io/postgres:17-alpine
    network:
      - podman-dns
    env:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: miniflux
    volumes:
      - /opt/miniflux/db:/var/lib/postgresql/data
    generate_systemd:
      path: /etc/systemd/system/
      new: true

- name: Start container
  containers.podman.podman_container:
    name: miniflux
    image: docker.io/miniflux/miniflux:latest
    ports:
      - "80:8080"
    network:
      - podman-dns
    env:
      DATABASE_URL: postgres://miniflux:secret@db/miniflux?sslmode=disable
      RUN_MIGRATIONS: 1
      CREATE_ADMIN: 1
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: test123
    generate_systemd:
      path: /etc/systemd/system/
      new: true

- name: Start and enable service
  ansible.builtin.systemd:
    name: "container-{{ item }}.service"
    enabled: true
    state: started
  loop:
    - db
    - miniflux
