---
- name: Install qlcplus
  ansible.builtin.apt:
    name:
      - qlcplus
      - qlcplus-data

- name: Setup autostart
  ansible.builtin.template:
    src: qlcplus.service
    dest: /lib/systemd/system/qlcplus.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable service
  ansible.builtin.service:
    name: qlcplus.service
    daemon_reload: true
    enabled: true
    state: started
  notify: Reboot

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ qlcplus__repo }}"
    dest: "{{ qlcplus__working_dir }}"
  become_user: "{{ qlcplus__user }}"
